name: Security Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Dependency Check
        uses: dependency-check/DependencyCheck@v3.3.2
        with:
          project: 'YourProjectName'
          scan-path: '.'
          format: 'ALL'
          fail-on-cvss: '7'
  
  horusec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Install Horusec
        run: |
          curl -fsSL https://horusec.io/bin/install.sh | bash

      - name: Run Horusec
        run: |
          horusec start -p . -a -D

      - name: Upload Horusec Report
        uses: actions/upload-artifact@v3
        with:
          name: horusec-report
          path: './.horusec/horusec-report.json'
