name: Security Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Install Dependency Check
        run: |
          curl -LO https://github.com/jeremylong/DependencyCheck/releases/download/v7.0.4/dependency-check-7.0.4-release.zip
          unzip dependency-check-7.0.4-release.zip -d dependency-check
          ls -l dependency-check/bin

      - name: Run Dependency Check
        run: |
          ./dependency-check/bin/dependency-check.sh --project YourProjectName --scan . --format "ALL" --failOnCVSS 7
      
      - name: Upload Dependency Check Report
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-report
          path: ./dependency-check-report

  horusec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Install Horusec
        run: |
          curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec-install/master/scripts/install.sh | bash
          echo 'export PATH=$PATH:/usr/local/bin' >> $GITHUB_ENV

      - name: Run Horusec
        run: |
          horusec start -p . -a -D

      - name: Upload Horusec Report
        uses: actions/upload-artifact@v3
        with:
          name: horusec-report
          path: './.horusec/horusec-report.json'
